# Copyright (C) 2013-2023 Karlsruhe Institute of Technology
#
# This file is part of syris.
#
# This library is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library. If not, see <http://www.gnu.org/licenses/>.

"""Cameras used by experiments."""

import logging
import pkg_resources
import numpy as np
import quantities as q
import scipy.interpolate as interp
import syris.gpu.util as gutil
import syris.geometry as geom
from syris.geometry import Trajectory
from syris.bodies.base import MovableBody
from syris import config as cfg
from syris.imageprocessing import bin_image, decimate
from syris.math import fwnm_to_sigma
from syris.geometry import Z_AX

LOG = logging.getLogger(__name__)


def is_fps_feasible(fps, exp_time):
    """Determine whether frame rate given by *fps* can be accomplished with
    the exposure time *exp_time*. It is only possible to set frame rates
    for which :math:`exposure\ time <= 1 / fps`.
    """
    return exp_time <= 1.0 / fps


def is_length(param):
    return (
        isinstance(param, q.Quantity)
        and param.dimensionality.simplified == q.m.dimensionality.simplified
    )


class Camera(MovableBody):
    """Base class representing a camera."""

    def __init__(
        self,
        pixel_size=None,
        gain=None,
        dark_current=None,
        amplifier_sigma=None,
        bits_per_pixel=None,
        shape=None,
        quantum_efficiencies=None,
        wavelengths=None,
        exp_time=1 * q.s,
        fps=1 / q.s,
        dtype=np.ushort,
        focal_length=None,
        optical_axis=None,
        source_detector_distance=None,
        trajectory=None,
        parallel=True,
    ):
        """Create a camera with *pixel_size*, *gain* specifying :math:`\frac{counts}{e^-}`,
        *dark_current* as mean number of electrons present without incident light, *amplifier_sigma*
        is the sigma of the normally distributed electron noise given by camera electronics,
        *bit_per_pixel* is the number of bits holding the pixel grey value, *quantum_efficiencies*
        are the quantum efficiencies at *wavelengths*, *exp_time* is the exposure time and *fps* are
        Frames Per Second which are generated by the camera (exposure time is independent from fps,
        i.e.  e.g.  fps can be set to 1000 and exposure time to 1 \mu s, but it cannot exceed
        :math:`1/fps` s).  *dtype* is the sensor output data type. If the values given are
        incompatible, the frame rate is adjusted to the exposure time.
        """
        if not isinstance(pixel_size, q.Quantity):
            raise TypeError("pixel_size must be a quantities object (e.g., 10 * q.m)")
        self._pixel_size = pixel_size.rescale(cfg.UNIT)
        self._shape = shape
        self.gain = gain
        self.dark_current = dark_current
        self.amplifier_sigma = amplifier_sigma
        self.bpp = bits_per_pixel
        self._quantum_efficiencies = quantum_efficiencies
        self._wavelengths = wavelengths
        self.dtype = dtype
        self._last_input_shape = None
        self._psf = None
        self._source_detector_distance = source_detector_distance
        self._focal_length = focal_length

        if source_detector_distance is not None:
            self._source_detector_distance = source_detector_distance.rescale(cfg.UNIT)

        if focal_length is not None:
            self._focal_length = focal_length.rescale(cfg.UNIT)

        self.update_viewport_dimensions()

        self.parallel = parallel

        if self._quantum_efficiencies is not None and self._wavelengths is not None:
            self._qe_tck = interp.splrep(
                self._wavelengths.rescale(q.nm).magnitude, self._quantum_efficiencies
            )
        if not is_fps_feasible(fps, exp_time):
            fps = 1 / exp_time.simplified
        self._exp_time = exp_time
        self._fps = fps

        if optical_axis is None:
            self._optical_axis = np.copy(Z_AX)
        else:
            self._optical_axis = optical_axis

        if trajectory is None:
            trajectory = Trajectory([(0, 0, 0)] * cfg.UNIT, pixel_size)

        super(Camera, self).__init__(trajectory)

    def _to_cuda_vector(self, quantity_vec, w_val=0.0):
        """
        Converts a 3D vector (either a quantities vector or a plain array-like)
        to a 4D NumPy float array for CUDA.
        """
        try:
            vec = quantity_vec.rescale(cfg.UNIT).magnitude
        except AttributeError:
            vec = np.asarray(quantity_vec)

        vec_4d = np.append(vec, w_val)
        return vec_4d.astype(cfg.PRECISION.np_float)

    def update_fov(self):
        if self._focal_length is None:
            return
        angle = self._viewport_dimensions / (2 * self._focal_length)
        self._fov = 2 * np.arctan(angle.simplified)

    def update_viewport_dimensions(self):
        self._viewport_dimensions = self._pixel_size * self._shape
        self.update_fov()

    @property
    def u(self):
        """The local right-direction vector (x-axis) of the camera."""
        return self.transform_matrix[0:3, 0]

    @property
    def v(self):
        """The local up-direction vector (y-axis) of the camera."""
        return self.transform_matrix[0:3, 1]

    @property
    def w(self):
        """The local forward-direction vector (z-axis) of the camera."""
        return self.transform_matrix[0:3, 2]

    @property
    def _u_vec(self):
        """The right-direction vector as a dimensionless quantities array."""
        return self.transform_matrix[0:3, 0] * q.dimensionless

    @property
    def _v_vec(self):
        """The up-direction vector as a dimensionless quantities array."""
        return self.transform_matrix[0:3, 1] * q.dimensionless

    @property
    def _pixel_size_vec(self):
        """Ensures pixel size is a 2-element quantities array."""
        ps = self._pixel_size.rescale(cfg.UNIT)
        if ps.ndim == 0:
            return np.array([ps.item(), ps.item()]) * ps.units
        return ps

    # Cuda compatible properties
    @property
    def pixel_size(self):
        return self._pixel_size.rescale(cfg.UNIT)

    @pixel_size.setter
    def pixel_size(self, value):
        if not is_length(value):
            raise ValueError("Pixel size must be a length quantity")
        if value.size > 2:
            raise ValueError("Pixel size must be at most a 2D array")
        if np.any(value <= 0):
            raise ValueError("Pixel size must be greater than 0")
        self._pixel_size = value
        self.update_viewport_dimensions()
        self.update_fov()

    @property
    def source_point(self):
        """Calculates the source point based on the camera's position and orientation."""
        vec = self.position + self._source_detector_distance * self.w
        return self._to_cuda_vector(vec)

    @property
    def shape(self):
        ret = np.array(self._shape)
        if ret.size == 1:
            ret = np.array([ret, ret])
        return ret.astype(np.uint32)

    @shape.setter
    def shape(self, value):
        if value.shape[0] > 2:
            raise ValueError("Resolution must be at most a 2D array")
        if np.any(value <= 0):
            raise ValueError("Resolution must be greater than 0")
        self._shape = value
        self.update_viewport_dimensions()
        self.update_fov()

    @property
    def kernel_shape_xy(self):
        """
        Returns the shape as (x, y) [width, height],
        contiguous, for CUDA kernels.
        """
        return self.shape[::-1].copy()

    @property
    def kernel_pixel_size_xy(self):
        """
        Returns the pixel_size as (x, y) [ps_x, ps_y],
        contiguous, for CUDA kernels.
        """
        ret = self._pixel_size.rescale(cfg.UNIT).magnitude
        if ret.size == 1:
            ret = np.array([ret, ret])
        ret = ret[::-1]
        return ret.astype(cfg.PRECISION.np_float)

    @property
    def focal_length(self):
        ret = self._focal_length.rescale(cfg.UNIT).magnitude
        return ret.astype(cfg.PRECISION.np_float)

    @focal_length.setter
    def focal_length(self, value):
        if not is_length(value):
            raise ValueError("Focal length must be a length quantity")
        if value <= 0:
            raise ValueError("Focal length must be greater than 0")
        self._focal_length = value
        self.update_fov()

    @property
    def viewport_dimensions(self):
        ret = self._viewport_dimensions.rescale(cfg.UNIT).magnitude
        return ret.astype(cfg.PRECISION.np_float)

    @property
    def viewport_origin(self):
        return self._to_cuda_vector(self.position)

    @property
    def fov(self):
        self._fov = (
            2 * np.arctan(self.viewport_dimensions / (2 * self.focal_length)) * q.rad
        )
        ret = self._fov.magnitude
        return ret.astype(cfg.PRECISION.np_float)

    @property
    def viewport_basis_vectors(self):
        """Returns the camera's basis vectors as CUDA-compatible arrays."""
        return (
            self._to_cuda_vector(self.u),
            self._to_cuda_vector(self.v),
            self._to_cuda_vector(self.w),
        )

    @property
    def p00_corner(self):
        """
        Calculates the world coordinate of the top-left CORNER
        of the top-left pixel (0,0).
        """
        # Get dimensions as quantities objects
        viewport_dims = self._shape * self._pixel_size_vec

        # Vector from the camera's center to the top-left corner of the sensor
        vec_to_corner = (
            -(viewport_dims[1] / 2) * self._u_vec - (viewport_dims[0] / 2) * self._v_vec
        )

        # Calculate the final position vector with units
        final_vec = self.position + vec_to_corner

        # Convert to unitless CUDA vector at the very end
        return self._to_cuda_vector(final_vec)

    @property
    def focal_point(self):
        """Calculates the focal point in world coordinates."""
        vec = self.position - self._focal_length * self.w
        return self._to_cuda_vector(vec)

    @property
    def viewport_center(self):
        return self._to_cuda_vector(self.position)

    @property
    def wavelengths(self):
        return self._wavelengths

    @property
    def exp_time(self):
        return self._exp_time

    @exp_time.setter
    def exp_time(self, exp_time):
        if not is_fps_feasible(self.fps, exp_time):
            fmt = "Exposure time {} not possible for FPS {}, setting FPS to {}"
            LOG.debug(fmt.format(exp_time, self.fps, 1 / exp_time.simplified))
            self._fps = 1 / exp_time.simplified
        self._exp_time = exp_time.simplified

    @property
    def fps(self):
        return self._fps

    @fps.setter
    def fps(self, fps):
        if not is_fps_feasible(fps, self.exp_time):
            fmt = (
                "FPS {} not possible for exposure time {}, setting exposure time to {}"
            )
            LOG.debug(fmt.format(fps, self.exp_time, 1 / fps.simplified))
            self._exp_time = 1 / fps.simplified
        self._fps = fps.simplified

    @property
    def max_grey_value(self):
        return 2**self.bpp - 1

    def get_quantum_efficiency(self, wavelength):
        """Get quantum efficiency [dimensionless] at *wavelength*."""
        return interp.splev(wavelength.rescale(q.nm).magnitude, self._qe_tck)

    def get_image(
        self, photons, shot_noise=True, amplifier_noise=True, psf=True, queue=None
    ):
        """Get digital counts image from incoming *photons*. The resulting image is based on the
        incoming photons and dark current. We apply noise based on EMVA 1288 standard according to
        which the variance :math:`\sigma_y^2 = K^2 ( \sigma_e^2 + \sigma_d^2 ) + \sigma_q^2`, where
        :math:`K` is the system gain, :math:`\sigma_e^2` is the poisson- distributed shot noise
        variance, :math:`\sigma_d^2` is the normal distributed electronics noise variance and
        :math:`\sigma_q^2` is the quantization noise variance. If *shot_noise* is False don't apply
        it. If *amplifier_noise* is False don't apply it as well. If *psf* is False don't apply the
        point spread function.
        """
        if self._last_input_shape != photons.shape:
            self._last_input_shape = photons.shape
            self._bin_factor = (
                photons.shape[0] / self.shape[0],
                photons.shape[1] / self.shape[1],
            )

        if queue is None:
            queue = cfg.OPENCL.queue

        # Shot noise
        # Adjust dark current for later binning and gain
        dark = float(self.dark_current) / self._bin_factor[0] / self._bin_factor[1]
        electrons = dark + gutil.get_host(photons)

        if self._bin_factor != (1, 1):
            if psf:
                sigma = (
                    fwnm_to_sigma(self._bin_factor[0]),
                    fwnm_to_sigma(self._bin_factor[1]),
                )
                small = decimate(electrons, self.shape, sigma=sigma, queue=queue)
            else:
                small = bin_image(electrons, self.shape, queue=queue)
            electrons = gutil.get_host(small)

        if shot_noise:
            electrons = np.random.poisson(electrons)

        if amplifier_noise and self.amplifier_sigma > 0:
            # Add electronics noise
            electrons = np.random.normal(electrons, self.amplifier_sigma)
            electrons[electrons < 0] = 0

        counts = self.gain * electrons

        # Cut the values beyond the maximum represented grey value given by
        # bytes per pixel.
        counts[counts > self.max_grey_value] = self.max_grey_value

        # Apply quantization noise
        return counts.astype(self.dtype)

    def rotate_around(self, angle, axis, pivot):
        """
        Rotates the body around an absolute world-space pivot point.
        This is a 'global' or 'orbit' transformation.

        :param angle: The angle of rotation (with units).
        :param axis: The axis of rotation
        :param pivot: The absolute world coordinate to orbit around.
        """
        # Create the global rotation matrix using the low-level function
        # This matrix performs the T * R * T^-1 operation.
        M_orbit = geom.rotate(angle, axis, shift=pivot)

        # 2. Apply this matrix as a GLOBAL (pre-multiplication) transform
        self.apply_transformation(M_orbit)

    def look_at(self, target_point):
        """
        Rotates the camera to look at a specific target point in world space,
        while keeping its current position.
        ...
        """
        LOG.debug(f"Camera {self} looking at {target_point}")

        # --- Get Vectors & Handle Units ---
        current_pos = self.position.simplified
        try:
            target_pos = target_point.simplified
        except AttributeError:
            target_pos = np.asarray(target_point, dtype=cfg.PRECISION.np_float)

        global_up = self._orientation

        # --- Calculate New Axes (Unitless) ---

        # W (Forward) vector: Points from camera to target
        forward_vec = geom.normalize(target_pos - current_pos)

        if np.linalg.norm(forward_vec) < 1e-9:
            return  # At target, no change

        # U (Right) vector
        # (Handle edge case of looking straight up/down)
        if abs(np.dot(global_up, forward_vec)) > 0.9999:
            # We are looking along the global_up axis.
            # Use X_AX as a temporary 'right' to find a 'down'.
            down_vec = geom.normalize(np.cross(geom.X_AX, forward_vec))
            right_vec = geom.normalize(np.cross(forward_vec, down_vec))
        else:
            right_vec = geom.normalize(np.cross(global_up, forward_vec))
            # V (Down) vector: Must be U x W
            down_vec = geom.normalize(np.cross(right_vec, forward_vec))

        # --- Build New 4x4 Matrix ---
        new_matrix = self.transform_matrix
        new_matrix[:3, 0] = right_vec  # U
        new_matrix[:3, 1] = down_vec  # V
        new_matrix[:3, 2] = forward_vec  # W
        self.transform_matrix = new_matrix


def make_pco_dimax():
    """Make a pco.dimax camera."""
    lam, qe = np.load(
        pkg_resources.resource_filename(__name__, "data/dimax_quantum_efficiencies.npy")
    )
    lam = lam * q.m

    # Use a power of two padded value so that it's easier to use with FFT
    return Camera(
        11 * q.m,
        0.1,
        530.0,
        23.0,
        12,
        (2048, 2048),
        quantum_efficiencies=qe,
        wavelengths=lam,
    )
